version: '3.3'

services:
  nfs-server:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    # https://hub.docker.com/r/itsthenetwork/nfs-server-alpine
    #image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs-server
    privileged: true

    ports:
    - 2049:2049  # nfsv4 
    - 111:111
    - 111:111/udp
    - 32765:32765
    - 32765:32765/udp
    - 32767:32767
    - 32767:32767/udp
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - ./nfs-storage:/data
